
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Unit-test:

    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Fix permissions for mocha
      run: chmod +x ./node_modules/.bin/mocha
    - name: Run Tests
      run: npm test
  
  Security-test:
    needs: Unit-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Audit for vulnerabilities
      run: npm audit